Module4 task1
htmlacademy-javascript/1792191-keksobooking-23 pull request #3
Opened 2021-07-07 16:52 UTC by Aleks35245

2021-07-07 18:43 UTC, PavelNyukalo requested changes

2021-07-07 18:43 UTC, PavelNyukalo commented on js/main.js
> +  });
`location` - это встроенный объект браузера, поэтому он ругается, что такой объект уже есть
![image](https://user-images.githubusercontent.com/52506235/124810711-19b20280-df7b-11eb-9790-bf2840610d89.png)

Можешь просто функцию назвать, например, `createLocation`
И поскольку это функция, у нее забыл литералы `{}`

2021-07-07 18:43 UTC, PavelNyukalo commented on js/main.js
> +const creatOffer = () => {
`creatE`

2021-07-07 18:43 UTC, PavelNyukalo commented on js/main.js
> +  const FEATURESSHORT = FEATURES.slice(); //создаем дубль массива FEATURES, будем его сокращать до countArrayFeatures с помощью цикла for
По общей договоренности в верхнем регистре пишутся неизменяемые константы, например, число пи
```js
const PI = 3,14
```
В таком случае понятно, что эта константа не будет изменяться, и по критериям они все пишутся в начале файла (и еще разделяются `_` - `FEATURES_SHORT`). Здесь же можно просто переменную создать `featuresShot`

2021-07-07 18:43 UTC, PavelNyukalo commented on js/main.js
> +  SIMILARADVERT[authorIndex] = newAdvert;
1. В момент присваивания индексу функцию, ты просто указываешь на ссылку функции, не её результат - по итогу массив заполняется функциями (прототип от функции идет)
![image](https://user-images.githubusercontent.com/52506235/124811579-0bb0b180-df7c-11eb-93e7-69d300a62bd0.png)

А нам надо присваивать _**результат**_ функции

2. Если в функции `creatOffer` надо подставлять данные из объекта `location` - то необходимо куда-то записать результат создания локации и передавать его и в `creatOffer`, и в сам объект `location`, а иначе получается вот
![image](https://user-images.githubusercontent.com/52506235/124812477-1881d500-df7d-11eb-8b17-33e55d81e570.png)

2021-07-08 09:00 UTC, Aleks35245 commented on js/main.js
> +  });
Исправил:
- переименовал функцию в createLocation и соответственно все ссылки на нее
- добавил литералы {}

2021-07-08 09:02 UTC, Aleks35245 commented on js/main.js
> +const creatOffer = () => {
) Правильно я понял, что это не ошибка кода, а моя орфографическая ошибка в части правил корректного наименования переменных/функций и пр.?
Исправил.

2021-07-08 09:07 UTC, Aleks35245 commented on js/main.js
> +  });
Исправил:
- Переименовал функцию и все её "следы" (кстати как меняя наименование в одном месте автоматически изменить все "следы"?)
- добавил литералы

2021-07-08 09:12 UTC, Aleks35245 commented on js/main.js
> +  const FEATURESSHORT = FEATURES.slice(); //создаем дубль массива FEATURES, будем его сокращать до countArrayFeatures с помощью цикла for
Понял тебя. Я подглядывал в "Учебный проект: нас орда" - сделал по аналогии - там так (массивы в верхнем регистре). Надо бы подсказать Академии, чтобы они поправили, а-то студенты же берут с них пример.
Исправил.

2021-07-08 10:15 UTC, Aleks35245 commented on js/main.js
> +  SIMILARADVERT[authorIndex] = newAdvert;
Создал отдельные const под координаты, на базе их собираю location и offer.address.
Из-за того, что  location и offer.address должны по логике иметь одинаковые значения, то поместил const под координаты и функции createLocation и createOffer.
Исправил

2021-07-08 15:44 UTC, PavelNyukalo commented on js/main.js
> +const creatOffer = () => {
Да, все верно

2021-07-08 15:57 UTC, PavelNyukalo requested changes

2021-07-08 15:57 UTC, PavelNyukalo commented on js/main.js
> +  };
Здесь надо еще чтобы функция возвращала объект, а то получается `undefined`

2021-07-08 15:57 UTC, PavelNyukalo commented on js/main.js
>    SIMILARADVERT[authorIndex] = newAdvert;
Здесь все еще присваиваешь элементам не _результат_ функции, а _саму_ функцию
![image](https://user-images.githubusercontent.com/52506235/124953768-db761b00-e02e-11eb-8daa-b7486b175f19.png)

А должны быть объекты - результаты функции, то есть ее надо вызывать
![image](https://user-images.githubusercontent.com/52506235/124953910-fcd70700-e02e-11eb-9ecf-91f6b13d5c3a.png)

2021-07-08 15:57 UTC, PavelNyukalo commented on js/main.js
> +for (let authorIndex = 0; authorIndex < AVATAR.length - 1; authorIndex++) { /* цикл
И кстати, используя строго меньше < мы не дозаполняем массив
![image](https://user-images.githubusercontent.com/52506235/124954011-1710e500-e02f-11eb-976d-152182fd34b4.png)

2021-07-09 15:48 UTC, Aleks35245 commented on js/main.js
> +  };
Павел, судя по скриншоту в последнем замечании с вычислением координат все нормально. Про какой Undefined ты говоришь? Я в VSC прописываю return, а он все равно ругается и предлагает return на круглые скобки заменить ().
![изображение](https://user-images.githubusercontent.com/83310456/125104239-d1fbba00-e0e5-11eb-8996-b7f3f4a1786f.png)

2021-07-09 16:54 UTC, Aleks35245 commented on js/main.js
> +  };
Если всеже неправильно, подскажи, пожалуйста, как правильно, а то я топчусь на одном месте, уже надо бежать дальше.

2021-07-11 17:31 UTC, PavelNyukalo approved these changes

2021-07-11 17:31 UTC, merged